#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    date:
      type: integer
      example: 20210307
      required: false
    states:
      type: integer
      example: 56
      required: false
    positive:
      type: integer
      example: 28756489
      required: false
    negative:
      type: integer
      example: 74582825
      required: false
    pending:
      type: integer
      example: 11808
      required: false
    hospitalizedCurrently:
      type: integer
      example: 40199
      required: false
    hospitalizedCumulative:
      type: integer
      example: 776361
      required: false
    inIcuCurrently:
      type: integer
      example: 8134
      required: false
    inIcuCumulative:
      type: integer
      example: 45475
      required: false
    onVentilatorCurrently:
      type: integer
      example: 2802
      required: false
    onVentilatorCumulative:
      type: integer
      example: 4281
      required: false
    dateChecked:
      type: string
      example: '2021-03-07T24:00:00Z'
      required: false
    death:
      type: integer
      example: 515151
      required: false
    hospitalized:
      type: integer
      example: 776361
      required: false
    totalTestResults:
      type: integer
      example: 363825123
      required: false
    lastModified:
      type: string
      example: '2021-03-07T24:00:00Z'
      required: false
    recovered:
      type: integer
      example: 0
      required: false
    total:
      type: integer
      example: 0
      required: false
    posNeg:
      type: integer
      example: 0
      required: false
    deathIncrease:
      type: integer
      example: 842
      required: false
    hospitalizedIncrease:
      type: integer
      example: 726
      required: false
    negativeIncrease:
      type: integer
      example: 131835
      required: false
    positiveIncrease:
      type: integer
      example: 41835
      required: false
    totalTestResultsIncrease:
      type: integer
      example: 1170059
      required: false
    hash:
      type: string
      example: a80d0063822e251249fd9a44730c49cb23defd83
      required: false
