#%RAML 1.0 DataType 
type: object
properties:
  date:
    type: integer
    example: 20210303
    required: false
  state:
    type: string
    example: NY
    required: false
  positive:
    type: integer
    example: 1650184
    required: false
  negative:
    type: integer
    example: 0
    required: false
  pending:
    type: integer
    example: 0
    required: false
  